name: Codex Developer
on:
  issues:
    types: [labeled]

jobs:
  codex:
    if: github.event.label.name == 'codex-ai'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Codex CLI
        run: npm install -g @openai/codex
          
      - uses: actions/checkout@v4
      - name: Create feature branch
        run: |
          git fetch origin
          git checkout -b codex/issue-${{ github.event.issue.number }}

      - name: Generate AI code
        shell: bash
        run: |
          export OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"
          export CODEX_QUIET_MODE=1
          retry codex -a full-auto -q "${{ github.event.issue.body }}"

      - name: Commit changes
        run: |
          git config user.name "github-actions[codex]"
          git config user.email "github-actions[codex]@users.noreply.github.com"
          git add .
          git commit -m "chore: AI-generated fix for issue: #${{ github.event.issue.title }}"

      - name: Create Pull Request
        run: |
          git push origin HEAD
          gh pr create \
            --title "AI: fix issue #${{ github.event.issue.title }}" \
            --body "Generated by Codex CLI in CI mode. See tests for validation." \
            --base main \
            --head codex/issue-${{ github.event.issue.number }}
